// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvpevhuhjimfnbfmhcri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cGV2aHVoamltZm5iZm1oY3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTg0MjAsImV4cCI6MjA2NTIzNDQyMH0.XgcgYPoliqpZNLLJOd8frRZ_5QJ-LlJC2-NsHHuHfxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);